### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by andrewzah** [tobymurray/mr_splashy_pants#9]
I assume your intent is to make this project open source, but without a license this code is under your copyright, and therefore is source-available, not open source. Thus I can't legally fork it and submit changes.

If you want to make it open source, you need to adopt a license from https://choosealicense.com/ (if that was your intent).

At least in the rust community, the [MIT license](https://choosealicense.com/licenses/mit/) is very common. Or dual licensing with MIT + [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/).

**Comment by tobymurray** [comment]
Great point - I've added the MIT license in d9cd68c
